# .github/workflows/main.yml
name: python-app

on: [push,workflow_dispatch]
env:
  IMAGE_NAME: mpaisa-app-api
  CONTAINER_NAME: mpaisa-app-api_container
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker availability
        run: docker info || echo "No Docker access"

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t $IMAGE_NAME .

      - name: Run Docker container
        run: |
          echo "Running Docker container with port mapping..."
          docker run -d --name $CONTAINER_NAME -p 5000:5000 $IMAGE_NAME

      - name: Display running containers
        run: docker ps

      - name: Run tests
        run: |
          pip install pytest
          echo "pytest has been installed"
          docker exec -it mpaisa-app-api_container curl -v http://localhost:5000/healthz
          curl -v http://localhost:5000/healthz || echo "5000 port cannnot be accessed"
          netstat -anpt | grep 5000
   #       pytest tests
          docker logs mpaisa-app-api_container
