# .github/workflows/main.yml
name: python-app

on: [push,workflow_dispatch]
env:
  IMAGE_NAME: python-demo
  CONTAINER_NAME: python-demo_container
  AZURE_WEBAPP_NAME: python-cicd-demo
jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker availability
        run: docker info || echo "No Docker access"

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t $IMAGE_NAME .

      - name: Run Docker container
        run: |
          echo "Running Docker container with port mapping..."
          docker run -d --name $CONTAINER_NAME -p 5000:5000 $IMAGE_NAME

      - name: Display running containers
        run: docker ps

      - name: Run tests
        run: |
          pip install pytest
          curl -v http://localhost:5000/healthz || echo "5000 port cannnot be accessed"
          pytest tests
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image for GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/python-demo:${{ github.sha }}
          docker tag $IMAGE_NAME $IMAGE_ID

      - name: Push Docker image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/python-demo:${{ github.sha }}
          docker push $IMAGE_ID
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'prod'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    needs: [build, analyze]
    steps:
      - name: deploy to Azure webapp
        uses: azure/webapps-deploy@v3.0.1
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ghcr.io/${{ github.repository_owner }}/python-demo:${{ github.sha }}

